a = int(input("Введите число: "))
b = int(input("Введите число: "))
print(f"Разность: {a-b}")
print(f"Сумма: {a+b}")
maximum = max(a, b)
print(f"Максимальное число: {maximum}")
minimum = min(a, b)
print(f"Минимальное число: {minimum}")